In [29]:
import pandas as pd
import numpy as np
import os

In [30]:
df = pd.read_csv("../data/global_ecommerce_sales.csv")

In [31]:
df.head()

,Order_ID,Order_Date,Customer_Name,Customer_Segment,Country,Region,Product_Category,Product_Name,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit,Payment_Method
0,ORD-11121,2023-01-02,Karen Suzuki,Corporate,United States,North America,Technology,Wireless Bluetooth Headphones,3,99.43,0,298.29,9.31,124.92,Cash on Delivery
1,ORD-11244,2023-01-02,John Johansson,Corporate,Spain,Europe,Technology,Mechanical Gaming Keyboard,4,97.93,20,313.38,14.31,83.62,Cash on Delivery
2,ORD-10325,2023-01-03,Jessica Garcia,Consumer,Mexico,North America,Office Supplies,Binder Clips Assorted 48pc,2,10.74,0,21.48,8.12,3.69,Credit Card
3,ORD-10467,2023-01-03,Clara Taylor,Corporate,Italy,Europe,Technology,Webcam HD 1080p,2,61.86,15,105.16,10.79,26.32,PayPal
4,ORD-11454,2023-01-05,Felix Thomas,Consumer,Italy,Europe,Furniture,Standing Desk Converter,4,330.67,20,1058.14,11.09,253.44,Credit Card

In [32]:
df.shape

(2000, 15)

In [33]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'Customer_Segment',
       'Country', 'Region', 'Product_Category', 'Product_Name', 'Quantity',
       'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Shipping_Cost',
       'Profit', 'Payment_Method'],
      dtype='object')

In [34]:
df.info

<bound method DataFrame.info of        Order_ID  Order_Date   Customer_Name Customer_Segment        Country  \
0     ORD-11121  2023-01-02    Karen Suzuki        Corporate  United States
1     ORD-11244  2023-01-02  John Johansson        Corporate          Spain
2     ORD-10325  2023-01-03  Jessica Garcia         Consumer         Mexico
3     ORD-10467  2023-01-03    Clara Taylor        Corporate          Italy
4     ORD-11454  2023-01-05    Felix Thomas         Consumer          Italy
...         ...         ...             ...              ...            ...
1995  ORD-10823  2025-12-31   Linda Nilsson         Consumer         France
1996  ORD-10896  2025-12-31    Ayumi Dubois         Consumer         France
1997  ORD-11148  2025-12-31   Barbara Jones         Consumer          Spain
1998  ORD-11519  2025-12-31    Maria Suzuki      Home Office          Spain
1999  ORD-11701  2025-12-31     Susan Russo      Home Office    South Korea

             Region        Product_Category                   Product_Name  \
0     North America              Technology  Wireless Bluetooth Headphones
1            Europe              Technology     Mechanical Gaming Keyboard
2     North America         Office Supplies     Binder Clips Assorted 48pc
3            Europe              Technology                Webcam HD 1080p
4            Europe               Furniture        Standing Desk Converter
...             ...                     ...                            ...
1995         Europe               Furniture         Folding Table Portable
1996         Europe  Clothing & Accessories            Cotton Formal Shirt
1997         Europe              Technology                Webcam HD 1080p
1998         Europe  Clothing & Accessories      Sports Water Bottle 750ml
1999   Asia Pacific  Clothing & Accessories      Sports Water Bottle 750ml

      Quantity  Unit_Price  Discount_Percent  Total_Sales  Shipping_Cost  \
0            3       99.43                 0       298.29           9.31
1            4       97.93                20       313.38          14.31
2            2       10.74                 0        21.48           8.12
3            2       61.86                15       105.16          10.79
4            4      330.67                20      1058.14          11.09
...        ...         ...               ...          ...            ...
1995         5      104.73                 0       523.65          19.10
1996        11       59.27                 5       619.37          20.94
1997         6       31.79                15       162.13          15.19
1998         5        9.50                 5        45.12          14.25
1999        11       28.27                 0       310.97          36.23

      Profit    Payment_Method
0     124.92  Cash on Delivery
1      83.62  Cash on Delivery
2       3.69       Credit Card
3      26.32            PayPal
4     253.44       Credit Card
...      ...               ...
1995  190.36            PayPal
1996  272.44            PayPal
1997   42.03     Bank Transfer
1998    7.12       Credit Card
1999  119.26       Credit Card

[2000 rows x 15 columns]>

In [35]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Total_Sales,Shipping_Cost,Profit
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000
mean,3.557500,73.329490,8.572500,242.279670,12.90212,79.436160
std,2.704506,79.311014,7.261274,382.583802,5.22319,137.573593
min,1.000000,3.030000,0.000000,2.420000,5.52000,-11.280000
25%,2.000000,18.757500,0.000000,41.227500,9.45750,6.865000
50%,3.000000,46.420000,10.000000,113.125000,11.84500,32.830000
75%,5.000000,90.250000,15.000000,266.552500,14.92000,90.297500
max,15.000000,472.560000,30.000000,3813.980000,40.44000,1373.630000

In [36]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
Customer_Segment    0
Country             0
Region              0
Product_Category    0
Product_Name        0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Shipping_Cost       0
Profit              0
Payment_Method      0
dtype: int64

In [37]:
missing_percent = (df.isnull().sum() / len(df)) * 100

missing_percent.sort_values(ascending=False)

Order_ID            0.0
Order_Date          0.0
Customer_Name       0.0
Customer_Segment    0.0
Country             0.0
Region              0.0
Product_Category    0.0
Product_Name        0.0
Quantity            0.0
Unit_Price          0.0
Discount_Percent    0.0
Total_Sales         0.0
Shipping_Cost       0.0
Profit              0.0
Payment_Method      0.0
dtype: float64

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
print(df.columns.tolist())

['Order_ID', 'Order_Date', 'Customer_Name', 'Customer_Segment', 'Country', 'Region', 'Product_Category', 'Product_Name', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Shipping_Cost', 'Profit', 'Payment_Method']

In [40]:
df.dtypes

Order_ID             object
Order_Date           object
Customer_Name        object
Customer_Segment     object
Country              object
Region               object
Product_Category     object
Product_Name         object
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Total_Sales         float64
Shipping_Cost       float64
Profit              float64
Payment_Method       object
dtype: object

In [41]:
df["Order_Date"] = pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)

print("Date data type:", df["Order_Date"].dtype)
print("Invalid dates:", df["Order_Date"].isna().sum())

Date data type: datetime64[ns]
Invalid dates: 0

In [42]:
df["Order_Year"] = df["Order_Date"].dt.year

In [43]:
df["Order_Month"] = df["Order_Date"].dt.month_name()

In [44]:
df["Order_YearMonth"] = df["Order_Date"].dt.to_period("M").astype(str)

In [45]:
df[["Order_Date", "Order_Year", "Order_Month", "Order_YearMonth"]].head()

  Order_Date  Order_Year Order_Month Order_YearMonth
0 2023-01-02        2023     January         2023-01
1 2023-01-02        2023     January         2023-01
2 2023-01-03        2023     January         2023-01
3 2023-01-03        2023     January         2023-01
4 2023-01-05        2023     January         2023-01

In [46]:
(df[["Quantity", "Unit_Price", "Total_Sales", "Shipping_Cost"]] < 0).sum()

Quantity         0
Unit_Price       0
Total_Sales      0
Shipping_Cost    0
dtype: int64

In [47]:
((df["Discount_Percent"] < 0) | (df["Discount_Percent"] > 100)).sum()

np.int64(0)

In [48]:
df["Order_ID"].nunique()

2000

In [49]:
df["Total_Sales"].sum()

np.float64(484559.33999999997)

In [50]:
df["Profit"].sum()

np.float64(158872.32)

In [51]:
df["Customer_Name"].nunique()

1534

In [52]:
df.to_csv("../data/cleaned_ecommerce_sales.csv", index=False)